version: "3.9"
services:
  db:
    image: postgres:16
    container_name: filrouge_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: filrouge
      POSTGRES_USER: filrouge
      POSTGRES_PASSWORD: filrouge
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-1
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DISABLE_POSTFIX: "true"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    depends_on:
      - db


volumes:
  pgdata:
